### PR TITLE
Removed sleep after each test case

### LINKED ISSUE #641: Performance issues with v0.6.0
I benchmarked v0.6.0 vs v0.5.0 twice; both results showed significant performance degradation in v0.6.0.

We should benchmark past commits to identify how this is introduced and solve it. Looking into significant pull requests can be a good starting point.

### PR DESCRIPTION
**Pull request by keremispirli**
Fixes #641

### CODE REVIEW

**Review by pjljvandelaar — COMMENTED** [review]
Why is LTS.11.5.csv included?

**Comment by keremispirli** [comment]
The performance is still bad, because we're still waiting for the TxsServer to exit.

[Benchmarks_0.5.0-removeSleep.xlsx](https://github.com/TorXakis/TorXakis/files/1927264/Benchmarks_0.5.0-removeSleep.xlsx)

**Comment by keremispirli** [comment]
@pjljvandelaar lts11.5.csv shouldn't have been included; thanks!

**Comment by pjljvandelaar** [comment]
Is serverProc and uiProc still needed?
Doesn't torxakis (uiProc) not start a server proc if needed on a unique address?
Is this still the legacy when we had to start the server ourselves at the right addresses?

**Comment by dnadales** [comment]
>Is serverProc and uiProc still needed?

No.

> Doesn't torxakis (uiProc) not start a server proc if needed on a unique address?

Yes.

> Is this still the legacy when we had to start the server ourselves at the right addresses

Yes.

So we should use only one executable for launching TorXakis.

**Review by dnadales — DISMISSED** [review]
Just make sure you remove the csv.

**Comment by pjljvandelaar** [comment]
I hope it solves the problem.
I just got
```
Moving Arms #model
...................................................==> sqatt-logs\explore-model-
test-2018-04-20_09-21-52.9828029_UTC\ReadWrite_Conflict_#model\Advanced_Stepper_
100\txsserver.out.log
> Found configuration file at `.torxakis.yaml`.
>
> TXSSERVER >>  Starting  .....
>
> TXSSERVER CMD >>  START
> TXSSERVER RSP <<  MACK txsserver starting:  "NLYBSTQVP4NB77Y.code1.emi.philips
.com" : 21949
> TXSSERVER RSP <<  PACK START
> TXSSERVER CMD >>  INIT examps\ReadWriteConflict\ReadWriteAdvanced.txs
> TXSSERVER RSP <<  MACK Solver "z3" initialized : Z3 [4.6.1 - build hashcode 45
0f3c9b459d]
> TXSSERVER RSP <<  MACK TxsCore initialized
> TXSSERVER RSP <<  MACK input files parsed:
> TXSSERVER RSP <<  MACK examps\ReadWriteConflict\ReadWriteAdvanced.txs
> TXSSERVER RSP <<  PACK INIT
> TXSSERVER CMD >>  STEPPER Model
> TXSSERVER RSP <<  MACK Stepper started
> TXSSERVER RSP <<  PACK STEPPER
> TXSSERVER CMD >>  STEP 100
> TXSSERVER RSP <<  MACK .....1: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK .....2: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK .....3: Act    { { ( Memory, [ Read(1) ] ) } }
> TXSSERVER RSP <<  MACK .....4: Act    { { ( Memory, [ Read(1) ] ) } }
> TXSSERVER RSP <<  MACK .....5: Act    { { ( Memory, [ Write(5) ] ) } }
> TXSSERVER RSP <<  MACK .....6: Act    { { ( Memory, [ Write(3) ] ) } }
> TXSSERVER RSP <<  MACK .....7: Act    { { ( Memory, [ Read(3) ] ) } }
> TXSSERVER RSP <<  MACK .....8: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK .....9: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....10: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....11: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....12: Act    { { ( Memory, [ Write(2) ] ) } }
> TXSSERVER RSP <<  MACK ....13: Act    { { ( Memory, [ Read(2) ] ) } }
> TXSSERVER RSP <<  MACK ....14: Act    { { ( Memory, [ Write(6) ] ) } }
> TXSSERVER RSP <<  MACK ....15: Act    { { ( Memory, [ Read(6) ] ) } }
> TXSSERVER RSP <<  MACK ....16: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....17: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....18: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....19: Act    { { ( Memory, [ Write(4) ] ) } }
> TXSSERVER RSP <<  MACK ....20: Act    { { ( Memory, [ Read(4) ] ) } }
> TXSSERVER RSP <<  MACK ....21: Act    { { ( Memory, [ Write(2) ] ) } }
> TXSSERVER RSP <<  MACK ....22: Act    { { ( Memory, [ Write(5) ] ) } }
> TXSSERVER RSP <<  MACK ....23: Act    { { ( Memory, [ Read(5) ] ) } }
> TXSSERVER RSP <<  MACK ....24: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....25: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....26: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....27: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....28: Act    { { ( Memory, [ Read(1) ] ) } }
> TXSSERVER RSP <<  MACK ....29: Act    { { ( Memory, [ Write(3) ] ) } }
> TXSSERVER RSP <<  MACK ....30: Act    { { ( Memory, [ Write(4) ] ) } }
> TXSSERVER RSP <<  MACK ....31: Act    { { ( Memory, [ Read(4) ] ) } }
> TXSSERVER RSP <<  MACK ....32: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....33: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....34: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....35: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....36: Act    { { ( Memory, [ Write(4) ] ) } }
> TXSSERVER RSP <<  MACK ....37: Act    { { ( Memory, [ Read(4) ] ) } }
> TXSSERVER RSP <<  MACK ....38: Act    { { ( Memory, [ Write(6) ] ) } }
> TXSSERVER RSP <<  MACK ....39: Act    { { ( Memory, [ Read(6) ] ) } }
> TXSSERVER RSP <<  MACK ....40: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....41: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....42: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....43: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....44: Act    { { ( Memory, [ Write(2) ] ) } }
> TXSSERVER RSP <<  MACK ....45: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....46: Act    { { ( Memory, [ Write(4) ] ) } }
> TXSSERVER RSP <<  MACK ....47: Act    { { ( Memory, [ Read(4) ] ) } }
> TXSSERVER RSP <<  MACK ....48: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....49: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....50: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....51: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....52: Act    { { ( Memory, [ Write(2) ] ) } }
> TXSSERVER RSP <<  MACK ....53: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....54: Act    { { ( Memory, [ Write(4) ] ) } }
> TXSSERVER RSP <<  MACK ....55: Act    { { ( Memory, [ Read(4) ] ) } }
> TXSSERVER RSP <<  MACK ....56: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....57: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....58: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....59: Act    { { ( Memory, [ Read(1) ] ) } }
> TXSSERVER RSP <<  MACK ....60: Act    { { ( Memory, [ Read(1) ] ) } }
> TXSSERVER RSP <<  MACK ....61: Act    { { ( Memory, [ Write(5) ] ) } }
> TXSSERVER RSP <<  MACK ....62: Act    { { ( Memory, [ Write(3) ] ) } }
> TXSSERVER RSP <<  MACK ....63: Act    { { ( Memory, [ Read(3) ] ) } }
> TXSSERVER RSP <<  MACK ....64: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....65: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....66: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....67: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....68: Act    { { ( Memory, [ Write(4) ] ) } }
> TXSSERVER RSP <<  MACK ....69: Act    { { ( Memory, [ Write(2) ] ) } }
> TXSSERVER RSP <<  MACK ....70: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....71: Act    { { ( Memory, [ Read(1) ] ) } }
> TXSSERVER RSP <<  MACK ....72: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....73: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....74: Act    { { ( Memory, [ Write(2) ] ) } }
> TXSSERVER RSP <<  MACK ....75: Act    { { ( Memory, [ Read(2) ] ) } }
> TXSSERVER RSP <<  MACK ....76: Act    { { ( Memory, [ Read(2) ] ) } }
> TXSSERVER RSP <<  MACK ....77: Act    { { ( Memory, [ Write(6) ] ) } }
> TXSSERVER RSP <<  MACK ....78: Act    { { ( Memory, [ Write(3) ] ) } }
> TXSSERVER RSP <<  MACK ....79: Act    { { ( Memory, [ Read(3) ] ) } }
> TXSSERVER RSP <<  MACK ....80: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....81: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....82: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....83: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....84: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....85: Act    { { ( Memory, [ Write(2) ] ) } }
> TXSSERVER RSP <<  MACK ....86: Act    { { ( Memory, [ Write(4) ] ) } }
> TXSSERVER RSP <<  MACK ....87: Act    { { ( Memory, [ Read(4) ] ) } }
> TXSSERVER RSP <<  MACK ....88: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....89: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....90: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....91: Act    { { ( Memory, [ Write(1) ] ) } }
> TXSSERVER RSP <<  MACK ....92: Act    { { ( Memory, [ Read(1) ] ) } }
> TXSSERVER RSP <<  MACK ....93: Act    { { ( Memory, [ Write(5) ] ) } }
> TXSSERVER RSP <<  MACK ....94: Act    { { ( Memory, [ Write(2) ] ) } }
> TXSSERVER RSP <<  MACK ....95: Act    { { ( Memory, [ Read(2) ] ) } }
> TXSSERVER RSP <<  MACK ....96: Act    { { ( Memory, [ Write(0) ] ) } }
> TXSSERVER RSP <<  MACK ....97: Act    { { ( Memory, [ Read(0) ] ) } }
> TXSSERVER RSP <<  MACK ....98: Act    { { ( Memory, [ Read(0) ] ) } }
--- EOF ---

==> sqatt-logs\explore-model-test-2018-04-20_09-21-52.9828029_UTC\ReadWrite_Conf
lict_#model\Advanced_Stepper_100\txsui.out.log
>
> TXS >>  TorXakis :: Model-Based Testing
>
> TXS >>  txsserver starting: "NLYBSTQVP4NB77Y.code1.emi.philips.com" : 21949
> TXS >>  Solver "z3" initialized : Z3 [4.6.1 - build hashcode 450f3c9b459d]
> TXS >>  TxsCore initialized
> TXS >>  input files parsed:
> TXS >>  examps\ReadWriteConflict\ReadWriteAdvanced.txs
> TXS >> TXS >>  Stepper started
> TXS >> TXS >>  .....1: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  .....2: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  .....3: Act { { ( Memory, [ Read(1) ] ) } }
> TXS >>  .....4: Act { { ( Memory, [ Read(1) ] ) } }
> TXS >>  .....5: Act { { ( Memory, [ Write(5) ] ) } }
> TXS >>  .....6: Act { { ( Memory, [ Write(3) ] ) } }
> TXS >>  .....7: Act { { ( Memory, [ Read(3) ] ) } }
> TXS >>  .....8: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  .....9: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....10: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....11: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....12: Act { { ( Memory, [ Write(2) ] ) } }
> TXS >>  ....13: Act { { ( Memory, [ Read(2) ] ) } }
> TXS >>  ....14: Act { { ( Memory, [ Write(6) ] ) } }
> TXS >>  ....15: Act { { ( Memory, [ Read(6) ] ) } }
> TXS >>  ....16: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....17: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....18: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....19: Act { { ( Memory, [ Write(4) ] ) } }
> TXS >>  ....20: Act { { ( Memory, [ Read(4) ] ) } }
> TXS >>  ....21: Act { { ( Memory, [ Write(2) ] ) } }
> TXS >>  ....22: Act { { ( Memory, [ Write(5) ] ) } }
> TXS >>  ....23: Act { { ( Memory, [ Read(5) ] ) } }
> TXS >>  ....24: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....25: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....26: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....27: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....28: Act { { ( Memory, [ Read(1) ] ) } }
> TXS >>  ....29: Act { { ( Memory, [ Write(3) ] ) } }
> TXS >>  ....30: Act { { ( Memory, [ Write(4) ] ) } }
> TXS >>  ....31: Act { { ( Memory, [ Read(4) ] ) } }
> TXS >>  ....32: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....33: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....34: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....35: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....36: Act { { ( Memory, [ Write(4) ] ) } }
> TXS >>  ....37: Act { { ( Memory, [ Read(4) ] ) } }
> TXS >>  ....38: Act { { ( Memory, [ Write(6) ] ) } }
> TXS >>  ....39: Act { { ( Memory, [ Read(6) ] ) } }
> TXS >>  ....40: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....41: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....42: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....43: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....44: Act { { ( Memory, [ Write(2) ] ) } }
> TXS >>  ....45: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....46: Act { { ( Memory, [ Write(4) ] ) } }
> TXS >>  ....47: Act { { ( Memory, [ Read(4) ] ) } }
> TXS >>  ....48: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....49: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....50: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....51: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....52: Act { { ( Memory, [ Write(2) ] ) } }
> TXS >>  ....53: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....54: Act { { ( Memory, [ Write(4) ] ) } }
> TXS >>  ....55: Act { { ( Memory, [ Read(4) ] ) } }
> TXS >>  ....56: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....57: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....58: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....59: Act { { ( Memory, [ Read(1) ] ) } }
> TXS >>  ....60: Act { { ( Memory, [ Read(1) ] ) } }
> TXS >>  ....61: Act { { ( Memory, [ Write(5) ] ) } }
> TXS >>  ....62: Act { { ( Memory, [ Write(3) ] ) } }
> TXS >>  ....63: Act { { ( Memory, [ Read(3) ] ) } }
> TXS >>  ....64: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....65: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....66: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....67: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....68: Act { { ( Memory, [ Write(4) ] ) } }
> TXS >>  ....69: Act { { ( Memory, [ Write(2) ] ) } }
> TXS >>  ....70: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....71: Act { { ( Memory, [ Read(1) ] ) } }
> TXS >>  ....72: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....73: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....74: Act { { ( Memory, [ Write(2) ] ) } }
> TXS >>  ....75: Act { { ( Memory, [ Read(2) ] ) } }
> TXS >>  ....76: Act { { ( Memory, [ Read(2) ] ) } }
> TXS >>  ....77: Act { { ( Memory, [ Write(6) ] ) } }
> TXS >>  ....78: Act { { ( Memory, [ Write(3) ] ) } }
> TXS >>  ....79: Act { { ( Memory, [ Read(3) ] ) } }
> TXS >>  ....80: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....81: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....82: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....83: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....84: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....85: Act { { ( Memory, [ Write(2) ] ) } }
> TXS >>  ....86: Act { { ( Memory, [ Write(4) ] ) } }
> TXS >>  ....87: Act { { ( Memory, [ Read(4) ] ) } }
> TXS >>  ....88: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....89: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....90: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....91: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ....92: Act { { ( Memory, [ Read(1) ] ) } }
> TXS >>  ....93: Act { { ( Memory, [ Write(5) ] ) } }
> TXS >>  ....94: Act { { ( Memory, [ Write(2) ] ) } }
> TXS >>  ....95: Act { { ( Memory, [ Read(2) ] ) } }
> TXS >>  ....96: Act { { ( Memory, [ Write(0) ] ) } }
> TXS >>  ....97: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....98: Act { { ( Memory, [ Read(0) ] ) } }
> TXS >>  ....99: Act { { ( Memory, [ Write(1) ] ) } }
> TXS >>  ...100: Act { { ( Memory, [ Read(1) ] ) } }
> TXS >>  PASS
> TXS >> TXS >>  txsserver closing "NLYBSTQVP4NB77Y.code1.emi.philips.com" : 219
49
>
> TXS >>  TorXakis :: Model-Based Testing  << End
>
--- EOF ---
```
Hence, I have an error. Yet, I still can't see why ;-(

**Review by pjljvandelaar — DISMISSED** [review]
I leave to merging to Kerem: I don't want to merge something that shouldn't be merged ;-)

**Comment by keremispirli** [comment]
@pjljvandelaar the same test fails in my machine due to test timeout.

The server logs you posted last change I did

**Comment by keremispirli** [comment]
@pjljvandelaar the same test failed in my machine due to test timeout.

The server logs you posted show that txsui actually succeeded but txsserver was killed before it could log the last two items. Do you still have the console output? It should tell why it failed at the end.

I moved handling of txsserver to one level up, so it starts before others and is killed by the timer in case of a timeout. If txsui finishes first, txsserver will not be killed so that it can complete its logging and gracefully exit.

**Review by pjljvandelaar — APPROVED** [review]
Just a little bit too late....

**Comment by keremispirli** [comment]
Benchmark results show that the performance degradation disappeared.
[Benchmarks_0.5.0-removeSleep_sm.xlsx](https://github.com/TorXakis/TorXakis/files/1938139/Benchmarks_0.5.0-removeSleep_sm.xlsx)

**Pull request merged**
