### PR TITLE
changed default value

### LINKED ISSUE #181: IncrementChoice should be the default for random value generation
Currently, TrueBins is the default.
Yet, Z3 and cvc4 issues discovered by IncrementChoice are solved, so
IncrementChoice could become the default.

In benchmark:
Truebins:
Timer "ta1" stop = 2017-08-29 17:13:58.1542369 -- Duration = 15.0937522s
Timer "ta_b" stop = 2017-08-29 17:14:19.9198679 -- Duration = 21.7343749s
IncrementChoice:
Timer "ta1" stop = 2017-08-30 08:13:31.4411985 -- Duration = 4.67191s
Timer "ta_b" stop = 2017-08-30 08:13:36.9568611 -- Duration = 5.5000384s

### PR DESCRIPTION
**Pull request by pjljvandelaar**
fixes #181

### CODE REVIEW

**Comment by capitanbatata** [comment]
`Adder` test is failing:

SUT log:

```
Starting 1 adders.
Starting an adder listening on port 7890
Adders on port 7890 received input: Plus(465043522025472016,2003597090973319935)
java.lang.NumberFormatException: For input string: "465043522025472016"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at Adder.startAdder(Adder.java:79)
	at Adder.run(Adder.java:27)
	at java.lang.Thread.run(Thread.java:748)
```

TXSUI log

```

TXS >>  txsserver starting: "localhost" : 54983
TXS >>  TorXakis :: Model-Based Testing

TXS >>  Solver initialized : Z3 [4.5.1 - build hashcode 0f1583309d08]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >>  examps/Adder/Adder.txs
TXS >>  Tester started
TXS >>  .....1: IN: Act { { ( Action, [ Plus(465043522025472016,2003597090973319935) ] ) } }
TXS >>  .....2: OUT: No Output (Quiescence)
TXS >>  Expected:
TXS >>  [ ( { Result[ $Result$1162$1$1$ ] }, [], [ ( 2468640612998791951 == $Result$1162$1$1$ ) ] ) ]
TXS >>  FAIL: No Output (Quiescence)
TXS >>  txsserver closing "localhost" : 54983
TXS <<  TXS <<  TXS <<  TXS <<  
TXS >>  TorXakis :: Model-Based Testing  << End
```

**Comment by pjljvandelaar** [comment]
Known issue in Adder: it assumes 32 bit integers.....

**Comment by capitanbatata** [comment]
GCD tests (Dispatch process 7) also times out on big integers. We could change the command parameters to solve this.

**Comment by pjljvandelaar** [comment]
The test should pass....
I however discovered another problem: protecting from 32 bit overflow while generating numbers of > 2^64 will only rarely (2^32/2^64 = 2 ^-32) generate a random value.
You typically get the default (zero)!

I think we have to raise an issue to change the params for e.g. Queue examples....

**Comment by pjljvandelaar** [comment]
local results:
sqatt-0.1: test (suite: qa-test)


Examples.All
  Adder
WARNING: The presence of SMT solvers was not checked.
         First issue #47 needs to be resolved.
See: https://github.com/TorXakis/TorXakis/issues/47
    Basic
    State Automation
    Parallel adders
  Control Loop
    Stepper
    Spec Produce
    Spec Measure
    Spec Correct
.........    Multiple Loops Stepper
  Customers and Orders
    Customers & Orders Test
  Dispatch Process
    Process 01
    Process 02
    Process 03
    Process 04
    Process 05
    Process 05a
    Process 06
    Process 06a
    Process 07
    Process 08
    Process 09
    Process 10 - Data
    Process 12 - Unique ID (Wrong)
    Process 12 - Unique ID (Right)
  Echo
    Stepper
    Simulator
  Lucky People
.    Test 1
    Test 0
  Moving Arms
    Stepper Test
..    Purpose Stepper Test
  Point
    Stepper Test
    Purpose Stepper Test
  Read/Write Conflict
    ReadWriteConflict Stepper Test
    ReadWriteConflict Stepper7 Test
    ReadWriteConflict_Advanced Stepper Test
  Queue
    Stepper Test
    Stepper Test (Lossy)
    SUT Test
  Stimulus-Response
    Stimulus-Response Test 0
    Stimulus-Response Test 1
    Stimulus-Response Test 2
    Stimulus-Response Test 3
    Stimulus-Response Test 4

Finished in 1084.4432 seconds
42 examples, 0 failures

**Comment by pjljvandelaar** [comment]
Faster GCD algorithm: not repeat subtraction, but use modulo:
https://en.wikipedia.org/wiki/Euclidean_algorithm 
    IF b == 0 THEN  a 
              ELSE  gcd (b, a % b) 
    FI

**Pull request merged**
