### PR TITLE
Unittest/valexpr

### PR DESCRIPTION
**Pull request by pjljvandelaar**
Added more unit tests to ValExpr.
Experimented with Lenses: however since we want automatic simplifications (rewriting) 
we decided lenses are not used in this part.

### CODE REVIEW

**Comment by dnadales** [comment]
For some reason these builds are not using the cache which I just filled after a successful build ...

**Comment by keremispirli** [comment]
@capitanbatata it takes some time for AppVeyor caches to be updated. Even after that they can occasionally fail. Better to try again a while later.

**Comment by dnadales** [comment]
That's weird. Ok, then we need some patience :)

Thanks for the info!

**Comment by dnadales** [comment]
Ok, the cache was hit now. So hopefully the build will finish on time.

**Review by tretmans — APPROVED** [review]

**Pull request merged**
