### PR TITLE
Fixed 1 bug in LPE to mCRL2 translation

### PR DESCRIPTION
**Pull request by ikbendedjurre**
Fixed 1 bug in LPE to mCRL2 translation, namely https://github.com/TorXakis/TorXakis/issues/950#issue-574330357

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
Two questions:
* Is the (empty) dummy.txt file needed? Must the extension be txt? You are now violating the copyright requirement of TorXakis.
* Is the TODO needed? Kerem introduced the policy we shouldn't have them. For the more experimental software of LpeOps, I don't know whether this is the right policy. What do you think?

**Review by pjljvandelaar — CHANGES_REQUESTED** [review]
See my comment

**Comment by ikbendedjurre** [comment]
I did not have enough time to develop tests for the alternate linearization method, so the test directory is empty. This also means that git does not create the directory when cloning the repository afresh (at least at the time), so I added dummy.txt.

After refreshing my memory on how TorXakis works compared to mCRL2, the TODO note about hidden variables is redundant, because any hidden variables are introduced by the mCRL2 SUM operator of a summand (in other words, hidden variables become regular local variables in mCRL2).

Do you want me to make a new pull request?

**Comment by pjljvandelaar** [comment]
You can add empty directories in git using .gitignore files. See e.g. https://steindom.com/2013/01/24/add-empty-directory-git-repository and https://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository/932982#932982.

If the TODO is not needed than please remove, and update/ push to this pull request.

**Review by pjljvandelaar — APPROVED** [review]

**Pull request merged**
