### PR TITLE
improve naming

### PR DESCRIPTION
**Pull request by pjljvandelaar**
localized Product and Sum even more to ValExpr
(and not in StdTDefs)

@capitanbatata I don't know whether it interferes much with you pull request.

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
Local results: 
Examples.All
  Adder
WARNING: The presence of SMT solvers was not checked.
         First issue #47 needs to be resolved.
See: https://github.com/TorXakis/TorXakis/issues/47
    Basic
    State Automation
    Parallel adders
  Control Loop
    Stepper
    Spec Measure
    Spec Correct
...    Multiple Loops Stepper #long
  Customers and Orders
    Customers & Orders Test #long
  Dispatch Process
    Process 01
    Process 02
    Process 03
    Process 04
    Process 05
    Process 05a
    Process 06
    Process 06a
    Process 07
    Process 08
    Process 09
    Process 10 - Data
    Process 12 - Unique ID #long
    Process 12 - Unique ID (Wrong)
    Process 12 - Unique ID (Right)
  Echo
    Stepper
    Simulator
  Lucky People
    Examples Purpose Test
..    Lucky By Gender Test
    Random Lucky Test
  Moving Arms
    Stepper Test
    Purpose Stepper Test #long
  Point
    Stepper Test
    Purpose Stepper Test
  Read/Write Conflict
    ReadWriteConflict Stepper Test
    ReadWriteConflict Stepper7 Test
    ReadWriteConflict_Advanced Stepper Test
  Queue
    Stepper Test
    Stepper Test (Lossy)
    SUT Test
  Stimulus-Response
    Stimulus-Response Test 0
    Stimulus-Response Test 1
    Stimulus-Response Test 2
    Stimulus-Response Test 3
    Stimulus-Response Test 4

Finished in 603.6435 seconds
43 examples, 0 failures

Completed 2 action(s).

**Comment by capitanbatata** [comment]
It does interfere with my PR, so to prevent me from having to go through all the process of merging from develop again, I'd prefer to merge mine first after we discuss it tomorrow, and then merge this one, or take it along.

**Comment by pjljvandelaar** [comment]
What went wrong in Customers & Orders Test #long FAILED [1]?
What was the seed used? Is the log available?

**Comment by pjljvandelaar** [comment]
Hard to reproduce the failure:
C:\TorXakis\test\sqatt>stack test --test-arguments=--match=Customer
sqatt-0.1: test (suite: qa-test, args: --match=Customer)


Examples.All
  Customers and Orders
WARNING: The presence of SMT solvers was not checked.
         First issue #47 needs to be resolved.
See: https://github.com/TorXakis/TorXakis/issues/47
    Customers & Orders Test #long

Finished in 41.5865 seconds
1 example, 0 failures


C:\TorXakis\test\sqatt>stack test --test-arguments=--match=Customer
sqatt-0.1: test (suite: qa-test, args: --match=Customer)


Examples.All
  Customers and Orders
WARNING: The presence of SMT solvers was not checked.
         First issue #47 needs to be resolved.
See: https://github.com/TorXakis/TorXakis/issues/47
    Customers & Orders Test #long

Finished in 42.3836 seconds
1 example, 0 failures

**Pull request merged**
