### PR TITLE
fixing a lot of pedantic error (-Wall)

### PR DESCRIPTION
**Pull request by pjljvandelaar**
> stack build --fast --ghc-options -Wall
Not everything done yet (but end of day)

### CODE REVIEW

**Comment by keremispirli** [comment]
@capitanbatata looks like codeclimate complains about existing issues if there's a change on their lines.

**Comment by capitanbatata** [comment]
Code climate reports some new issues. Are we OK with those or do we want to fix them before we merge these changes?

**Comment by PierreVDL** [comment]
Code climate doesn't report new issues:
when a line is changed the issue is assumed to be removed.
when the changed line still contains an issue, it is considered a new issue!

I propose to accept this pull request!

**Comment by capitanbatata** [comment]
@PierreVDL @pjljvandelaar it is approved now. Feel free to sqash and merge it.

**Pull request merged**
