### PR TITLE
added powerpoint

### PR DESCRIPTION
**Pull request by pjljvandelaar**
This powerpoint was in the old archive.
Updated it to current archive and added it!

We want to use it at the workshop next week!

### CODE REVIEW

**Comment by capitanbatata** [comment]
I wouldn't store binary blobs in our github repository. Can't we use any other service for this purpose (Google docs, Dropbox, One Drive)?

**Comment by keremispirli** [comment]
@pjljvandelaar Why do we want this file to be part of our repository?

If it is enough to make it available for people who want to learn about CustomersOrders example, then we can use GitHub to store our files and put a link in our existing MD files: [CustomersOrders.pptx](https://github.com/TorXakis/TorXakis/files/1454312/CustomersOrders.pptx)

I can do the same thing for powerpoint files of LuckyPeople and StimulusResponse examples, too.

**Comment by pjljvandelaar** [comment]
I know git is not meant for binaries ... 

I would like one place to have all documentation available.
Otherwise we increase the risk of making changes only to a part of the documentation.

**Comment by pjljvandelaar** [comment]
@keremispirli Where does GitHub store binaries?

**Comment by keremispirli** [comment]
When you attach a file to any comment/issue, it's uploaded to GitHub and saved under your project. Then you can use the link to it anywhere you want. This can be used to host the file for users instead of including it in our repository.

In order to actually manage our documentation, though, we need a better solution. We already have [DMSF](https://esi-redmine.tno.nl/projects/torxakis/dmsf), but it is internal which means every time we update a file, we will have to re-upload to GitHub and update links in the repository. 

Ideal solution would be a place where we can store files and have public links to them. It is normally possible in OneDrive but TNO doesn't allow it. Maybe we can ask for a special OneDrive account for TorXakis that it's allowed? Or maybe there's a way to enable public links to files in DMSF?

**Comment by pjljvandelaar** [comment]
@keremispirli let's just merge this branch and make an issue about what to do with all pptx files / binary files

**Pull request merged**
