### PR TITLE
Moved One Axis Moving Arm test to model tests

### PR DESCRIPTION
**Pull request by keremispirli**
To investigate #673

### CODE REVIEW

**Review by pjljvandelaar — APPROVED** [review]

**Comment by keremispirli** [comment]
Do not delete the branch just yet; I set up hourly builds on this branch so that we can investigate.

**Comment by keremispirli** [comment]
Looks like tester messages can also get lost.
One Axis test, `Up` action from the tester is lost: https://semaphoreci.com/capitanbatata/torxakis/branches/movingarmmodeltest/builds/5

**Comment by pjljvandelaar** [comment]
Indeed... Up message seems to be lost....

**Comment by pjljvandelaar** [comment]
Original problem also occurs without test purpose. See e.g. https://semaphoreci.com/capitanbatata/torxakis/branches/movingarmmodeltest/builds/2

**Comment by keremispirli** [comment]
We have 51 builds so far. Do we need more or should I delete the scheduled hourly build and `movingArmModelTest` branch? @pjljvandelaar

**Comment by keremispirli** [comment]
**Reminder:** Don't delete the branch, or we lose all the records of the failing builds!

**Pull request merged**
