### PR TITLE
Made LPE-transform indirect

### PR DESCRIPTION
**Pull request by ikbendedjurre**
Made LPE-transform indirect, so that model initialization can contain non-ProcInst expressions.

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
I have some issues at the process level ;-(
1. Only one check is started, appveyor and codeclimate still need to be started
2. SemaphoreCI gives a new  error (despite that nothing is changed at our side)
I will look into it...

**Comment by pjljvandelaar** [comment]
```
Package libgmp3-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libgmp-dev libmpfr-dev:i386 libmpfr-dev
```
@dnadales Why is a development package needed? We didn't change anything, did we?

I hope libgmp-dev is already enough...

**Comment by pjljvandelaar** [comment]
@ikbendedjurre should we close this pull request without merging?

**Comment by ikbendedjurre** [comment]
> @ikbendedjurre should we close this pull request without merging?

Yeah, I messed this one up a little. #807 should work.

**Pull request closed without merging**
