### PR TITLE
Feat/deb package

### PR DESCRIPTION
**Pull request by dnadales**
Add scripts for creating linux packages and instructions on how to use them.

@ramon-janssen: Jan mentioned that you're using Linux. I've tested the installer in several Ubuntu variants, but if you have time feel free to check if the installer works on your machine as well.

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
It seems you forgot the copyright notice in some files you added

**Comment by dnadales** [comment]
Argh! The first line of a bash script should be `#!/bin/bash` but due to the copyright checker I have to change it to something non-standard :/ It'll be nice if this program would be smarter in these cases...

**Comment by dnadales** [comment]
Inserting the copyright in the shell scripts is breaking them :(

**Review by pjljvandelaar — APPROVED** [review]

**Comment by ramon-janssen** [comment]
Is the installer supposed to set the PATH-variables? After installation, I do not see any new executables.

**Comment by pjljvandelaar** [comment]
@capitanbatata can you answer @ramon-janssen ?

**Comment by dnadales** [comment]
> Is the installer supposed to set the PATH-variables? After installation, I do not see any new executables.

Thanks for testing this @ramon-janssen. The binaries should be installed in `usr/bin`. Which Linux dstro and version are you using?

**Comment by ramon-janssen** [comment]
@capitanbatata I am using Ubuntu 16.04.4 LTS. Note, I have installed/built various previous versions of torxakis, so this may be of influence: After running ``sudo apt-get install ~/Downloads/torxakis_0.6.0_amd64.deb -y``, the version of ``/usr/bin/torxakis`` is an old one (according to the info-command).

**Comment by dnadales** [comment]
> I am using Ubuntu 16.04.4

I've tested in that version, with a clean Ubuntu installation.

> the version of /usr/bin/torxakis is an old one

Maybe the installer is not overwriting the old version? But I guess you should have gotten an error message or warning. What happens if you run:

```sh
apt-get remove torxakis
```

and then install again?

**Comment by ramon-janssen** [comment]
I stated that I get 'an old one' but perhaps its better to be explicit: I now get version ``UNVERSIONED`` built at ``Mon 06/12/2017 10:01:59.98``. This version is installed in ``/usr/bin``, using the ``.deb``-installer of the nightly build, found at the releases-page.

I assumed that this version is old, but perhaps the unversioned-part is simply because of the nightly built?

**Comment by dnadales** [comment]
Then it seems that you have the right version installed. Maybe `/usr/bin/` is not in your `PATH`?

**Comment by ramon-janssen** [comment]
Indeed, it isn't (I have no idea why not). It seems that this should be in ``PATH`` by default, so this should not be a problem for any other user. In that case, the installation seems to work fine (although I haven't run any more tests than simply trying out Adder.txs).

**Comment by dnadales** [comment]
I guess it is a good idea to clarify in the `README` that `/usr/bin` should be in the `PATH`.

>  (although I haven't run any more tests than simply trying out Adder.txs).

I've run a couple of tests (using the stepper and the simulator), but I also haven't tested it extensively (we have only so much time...).

Thanks!

**Pull request merged**
