### PR TITLE
Issue/463 val expr package

### PR DESCRIPTION
**Pull request by pjljvandelaar**
First step in improving the structure of TorXakis

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
The codeclimate issue is caused by moving a file: minus one remark and plus a new remark!

**Comment by pjljvandelaar** [comment]
Does anybody know why I get `Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: The program 'happy' is required but it could not be found.` on semaphoreci?

We never had issues with happy....

**Comment by pjljvandelaar** [comment]
Why does the windows succeed yet the Linux one fail...
They both need happy ...

**Comment by pjljvandelaar** [comment]
@capitanbatata can you pick this up when I don't finish it today?
Since next week I am in Las Palmas

**Comment by capitanbatata** [comment]
>  can you pick this up when I don't finish it today?
Since next week I am in Las Palmas

Sure. Could you or Kerem merge my pr so that I can take up this on Monday?

**Comment by capitanbatata** [comment]
> Does anybody know why I get Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: The program 'happy' is required but it could not be found. on semaphoreci?

The error message contained the hint:

```text
No packages found in snapshot which provide a "happy" executable, which is a build-tool dependency of "defs"
Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595
```

So apparently the extra dependencies on the `stack_linux.yaml` file were causing the problem.

**Comment by pjljvandelaar** [comment]
Can't approve my own pull request 😁

**Comment by capitanbatata** [comment]
I'm starting to review this now, I spent most of the time yesterday tracking the cause of a [nasty bug](https://github.com/TorXakis/TorXakis/issues/532) that caused the `stop` command on `TorXakis` to hang.

 I assume when you asked me to take this PR over you meant "make the project build on Linux again", or are there any further changes you want me to make @pjljvandelaar ?

**Pull request merged**
