### PR TITLE
moved to lts 11.0

### PR DESCRIPTION
**Pull request by pjljvandelaar**
On [stackage](http://stackage.org) a new lts is released.

I tested it.
Found one issue: don't know whether it reproduces.
```
Failures:

  src\Sqatt.hs:473:
  1) Examples.All, Customers and Orders, Customers & Orders Test
       expected: Right ()
        but got: Left (UnexpectedException "ExitFailure (-1)")

Randomized with seed 1664203401
```
It seems to be caused by the `java` SUT which terminates with an exception 
since the socket is closed by `Torxakis`.
```
> java.net.SocketException: Connection reset
>       at java.net.SocketInputStream.read(Unknown Source)
>       at java.net.SocketInputStream.read(Unknown Source)
>       at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
>       at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
>       at sun.nio.cs.StreamDecoder.read(Unknown Source)
>       at java.io.InputStreamReader.read(Unknown Source)
>       at java.io.BufferedReader.fill(Unknown Source)
>       at java.io.BufferedReader.readLine(Unknown Source)
>       at java.io.BufferedReader.readLine(Unknown Source)
>       at CustomersOrders.lambda$getInputThread$1(CustomersOrders.java:87)
>       at java.lang.Thread.run(Unknown Source)
> java.net.SocketException: Connection reset
>       at java.net.SocketInputStream.read(Unknown Source)
>       at java.net.SocketInputStream.read(Unknown Source)
```
Is something changed in the libraries we use?
If so, we might have to change sqatt ;-(

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
Another error and a time out.....
How to proceed?

**Comment by pjljvandelaar** [comment]
@kerem you can review....
@damian let's merge this asap to prevent cache swapping....

**Comment by capitanbatata** [comment]
But I don't understand. There's a commit that says don't merge. Can we merge now or not?

**Comment by keremispirli** [comment]
That was previous commit, I didn't think of adding a "now merge" commit,
sorry :)

**Pull request merged**
