### PR TITLE
dded Dropbox example

### PR DESCRIPTION
**Pull request by tretmans**
Adds Dropbox example of CECIIS paper.

### CODE REVIEW

**Review by dnadales — DISMISSED** [review]
Nice example! :tada:

**Comment by dnadales** [comment]
It seems you have to add license notices 

```
00:00
AUTO SCROLL ONLINE WRAP ON
./examps/Dropbox/dropboxtest/sut2.sh
./examps/Dropbox/dropboxtest/sut1.sh
./examps/Dropbox/dropboxtest/sut0.sh
./examps/Dropbox/dropbox-ceciis19.txs
./examps/Dropbox/Readme.txt
#Files = 513
#Violations = 5
Fail
```

**Review by pjljvandelaar — COMMENTED** [review]
Is .TorXakis.yml file different from default .yml file? If so, why?
If not, please remove the file.

**Comment by tretmans** [comment]
.torxakis.yaml is different: sut_delta is one minute.

**Pull request closed without merging**
