### PR TITLE
added guard and enable/disable

### PR DESCRIPTION
**Pull request by pjljvandelaar**
subitems of #589

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
Issue with simulator.
@tretmans we have to solve this fundamentally...

**Comment by pjljvandelaar** [comment]
@keremispirli What went wrong with `Wrong value for: RandSolve_adtWidth FAILED [1]` on semaphoreCI?

**Comment by keremispirli** [comment]
@pjljvandelaar It doesn't show logs, and the change in this commit doesn't seem to have anything with that parameter. It may be a glitch, maybe "resource in use" again. I'll restart the build to see if it works.

**Comment by pjljvandelaar** [comment]
@keremispirli problem seems to be a glitch....
If it happens more often we have to investigate... For now we can move on ;-)

**Review by dnadales — APPROVED** [review]
So happy to see these changes happening at the smart constructors and not at the compiler ;)

**Pull request merged**
