### PR TITLE
Add the instructions for installing `TorXakis` on macOS.

### PR DESCRIPTION
**Pull request by capitanbatata**

### CODE REVIEW

**Comment by tretmans** [comment]
Ask Axel Belinfante to do a user test?

**Comment by pjljvandelaar** [comment]
Good idea to involve Axel!

**Comment by harcokuppens** [comment]
I discovered when building the brew recipe for torxakis:
Sometimes the ghc build from source with stack fails.   Jan Tretmans said he
also had this problem (under cygwin If I remember correctly), and the solution was just to retry  the build.
The reason is that ghc has some makefiles which do not handle parallel
builds well. Often it will go ok, but sometimes
it fails. You can prevent this failure by disallowing parallel running the
makefile builds by setting the environment
flag :

    export MAKEFLAGS=" -j1 "

The problem only appears when stack runs a makefile, but within stack itself
doing parallellisme is handled fine. Stack by default chooses the right
number of parallellisme depending on the number of cpu cures. The MAKEFLAGS
environment variable doesn't effect the parallellisme within stack itself.

So the installation instruction on the torxakis website for linux:

    stack setup
    stack install

should be changed into:

    export MAKEFLAGS=" -j1 "
    stack setup
    stack install

this will prevent some build failures.
If you look at the homebrew recipe at
https://github.com/TorXakis/homebrew-TorXakis/blob/master/Formula/torxakis.rb
then you can see I do something similar. (homebrew uses ENV.deparallelize ).

The reason that I had to really solve this problem was that the build had to
be reliable for the brew bot. Just restarting the build was not an option.
Note: something similar is done by
https://github.com/Homebrew/homebrew-core/blob/master/Formula/haskell-stack.rb


greetings
Harco

**Comment by capitanbatata** [comment]
@pjljvandelaar @tretmans I added a short version of the instructions on how to install on MacOS. 

Axel found an error when running `TorXakis` I'm gonna try and see if it occurs on Linux and Windows.

**Pull request merged**
