### PR TITLE
Issue133/cstr function call

### LINKED ISSUE #278: move to lts 9.6
When we move to lts 9.6 (https://www.stackage.org/lts-9.6)
we get alex-3.2.3 
I assume we can then start building pedantic (-Wall)

### PR DESCRIPTION
**Pull request by pjljvandelaar**
Resolves #278

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
I am fixing 3 TODO and one brackets.
Also noticed some issues with Dispatch 10 & 12 locally:

`JobOut(1100364377616711936,1,3)`
versus
`JobOut(1100364377616711936,5,3)`

Yet the processor of JobData(1100364377616711936,"PD0",1797,8856) is definitely not always 5.
Maybe some substitution is done to much ....

**Comment by keremispirli** [comment]
DisPro10 and 12 failed locally, too.

**Comment by pjljvandelaar** [comment]
Same TODO both fixed and new ;-(
```
TODO found 
New
286        elemShow (t,p)  | p > 0 = "( " ++ pshow t ++ " ^ "  ++ show p ++ " )"   -- TODO: TorXakis doesn't support Power (not even x ^ integer)
Severity: Minor
Found in sys/defs/src/TxsShow.hs by fixme

TODO found 
 Fixed
Severity: Minor
Found in sys/defs/src/TxsShow.hs by fixme
```

**Comment by pjljvandelaar** [comment]
https://github.com/TorXakis/TorXakis/blob/develop/examps/DispatchProcess/spec/DisPro10-data.txs
has 
```processors [ Job2Proc, Finish ] ( 5 )```
yet, https://github.com/TorXakis/TorXakis/blob/develop/examps/DispatchProcess/sut/DispatchProcess.java
has 
```public static final int nrofProcessors = 4;```

Why was this never discovered?

**Comment by pjljvandelaar** [comment]
bug found: parsing in Eval had one (unused) argument to many...
I removed it everywhere else ;-)

**Comment by pjljvandelaar** [comment]
Yes, holidays....
everything seems fine again!

**Comment by keremispirli** [comment]
Related to #133

**Pull request merged**
