### PR TITLE
removed GHC-OPTIONS

### PR DESCRIPTION
**Pull request by pjljvandelaar**
remove no warn name shadwoing flags

Still 5 todo? or only two?

  C:\TorXakis\sys\behavedefs\src\BTShow.hs (1 hit)
             Line 8: {-# OPTIONS_GHC -fno-warn-orphans #-}
  C:\TorXakis\sys\server\test\CmdLineParserSpec.hs (1 hit)
             Line 6: {-# OPTIONS_GHC -fno-warn-orphans #-}
  C:\TorXakis\sys\server\test\Spec.hs (1 hit)
             Line 7: {-# OPTIONS_GHC -F -pgmF hspec-discover #-}
  C:\TorXakis\sys\valexpr\test\Spec.hs (1 hit)
             Line 6: {-# OPTIONS_GHC -F -pgmF hspec-discover #-}
  C:\TorXakis\test\sqatt\test\Spec.hs (1 hit)
             Line 7: {-# OPTIONS_GHC -F -pgmF hspec-discover #-}

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
@capitanbatata are the GHC OPTIONS for HSPEC mandatory?

**Comment by dnadales** [comment]
Yes. They are needed for test discovery

**Review by dnadales — DISMISSED** [review]

**Comment by pjljvandelaar** [comment]
Strange 'stack build' and 'stack test' executed fine on my laptop....
But 'elem' seems still shadowing....

**Comment by dnadales** [comment]
Are you sure that you're running the `hspec` tests? Maybe they are silently ignored:

https://hspec.github.io/hspec-discover.html

**Comment by pjljvandelaar** [comment]
Seemed that some packages missed -Wall and -Werror in the ghc-options of their test set.

**Review by dnadales — APPROVED** [review]

**Pull request merged**
