### PR TITLE
added smart choice operator

### PR DESCRIPTION
**Pull request by pjljvandelaar**
@CarstenRuetz I have update some tests to the new choice operator.
I have found (and solved) some issues in your test cases (Using channel B in a ProcDef with only channel A)

### CODE REVIEW

**Comment by pjljvandelaar** [comment]
Solves sub item of https://github.com/TorXakis/TorXakis/issues/589

**Comment by pjljvandelaar** [comment]
@tretmans I propose later a new NComp is added based on the LPE standard form (instead of StAut which is now removed). Agree?

**Comment by pjljvandelaar** [comment]
fixes sub issue in #589

**Review by CarstenRuetz — DISMISSED** [review]
fine by me.

**Comment by keremispirli** [comment]
Somehow these changes (as of 8c7c5db0) seem to counter the performance degradation which is caused by the additional 5s sleep at the end of every test (#641), but doesn't provide significant improvement when compared to fixed version (#650).

[Benchmarks_removeSleep_874ed8a-smartChoice_8c7c5db0.xlsx](https://github.com/TorXakis/TorXakis/files/1938222/Benchmarks_removeSleep-smartChoice.xlsx)
[Benchmarks_0.5.0-smartChoice_8c7c5db0.xlsx](https://github.com/TorXakis/TorXakis/files/1938223/Benchmarks_0.5.0-smartChoice_8c7c5db0.xlsx)

The commit 8c7c5db0 was selected because it's before merging LTS11.5 in. Do we want new measurements with latest changes in both develop and this branch? Or do we merge regardless?

**Comment by keremispirli** [comment]
Removed the "removedStAut" commit with interactive rebase. After merging this to develop, I'll rebase that commit on to the latest develop and create a branch from that.

**Review by keremispirli — APPROVED** [review]

**Comment by keremispirli** [comment]
According to benchmark, this change improved one case by 55%: "Synchronization/6   sequential processes synchronizing in two actions"
Most other cases slightly decreased though.
[Benchmarks_smartChoiceEffect.xlsx](https://github.com/TorXakis/TorXakis/files/1966765/Benchmarks_smartChoiceEffect.xlsx)

**Pull request merged**
